version: "3.8"
services:
  php:
    container_name: tanksbattle_php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html
  nginx:
    container_name: tanksbattle_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mongo-express:
    container_name: tanksbattle_mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://root:root@host.docker.internal:27017/admin?ssl=false"	
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    container_name: tanksbattle_mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongo-compose-network
networks: 
    mongo-compose-network:
      driver: bridge